# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[ ](bold dimmed green)"
error_symbol = "[✗](bold red)"

[package]
disabled = true

[battery]
full_symbol = "   "
charging_symbol = "  "
discharging_symbol = "  ﮊ  "

[[battery.display]]
threshold = 10
style = "bold red"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold dimmed green"
truncation_symbol = ".../"
home_symbol = " "
read_only = "  "
read_only_style = "white"

[git_branch]
symbol = " "
style = "bold blue"

[hostname]
ssh_only = false
style = "bold dimmed green"

[memory_usage]
disabled = false

[python]
symbol = " "

[username]
show_always = false

[cmd_duration]
disabled = true
